language: generic
sudo: required
services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t oraserv/fib-frontend:test -f ./frontend/Dockerfile.dev ./frontend

scripts:
  - docker run -e CI=true oraserv/fib-frontend:test npm test

after_success:
  - docker build -t oraserv/fib-backend:latest -t oraserv/fib-backend:$GIT_SHA -f ./backend/Dockerfile ./backend
  - docker build -t oraserv/fib-worker:latest -t oraserv/fib-worker:$GIT_SHA -f ./worker/Dockerfile ./worker
  - docker build -t oraserv/fib-frontend:latest -t oraserv/fib-frontend:$GIT_SHA -f ./frontend/Dockerfile ./frontend
  - docker build -t oraserv/fib-nginx:latest -t oraserv/fib-nginx:$GIT_SHA -f ./nginx/Dockerfile ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push oraserv/fib-frontend:latest
  - docker push oraserv/fib-frontend:$GIT_SHA
  - docker push oraserv/fib-backend:latest
  - docker push oraserv/fib-backend:$GIT_SHA
  - docker push oraserv/fib-worker:latest
  - docker push oraserv/fib-worker:$GIT_SHA
  - docker push oraserv/fib-nginx:latest
  - docker push oraserv/fib-nginx:$GIT_SHA
