language: generic
sudo: required
services: docker

before_install:
  - docker build -t oraserv/fib-frontend:test -f ./frontend/Dockerfile.dev ./frontend

scripts:
  - docker run -e CI=true oraserv/fib-frontend:test npm test

after_success:
  - docker build -t oraserv/fib-backend:pro -f ./backend/Dockerfile ./backend
  - docker build -t oraserv/fib-worker:pro -f ./worker/Dockerfile ./worker
  - docker build -t oraserv/fib-frontend:pro -f ./frontend/Dockerfile ./frontend
  - docker build -t oraserv/fib-nginx:pro -f ./nginx/Dockerfile ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oraserv/fib-backend:pro
  - docker push oraserv/fib-worker:pro
  - docker push oraserv/fib-frontend:pro
  - docker push oraserv/fib-nginx:pro

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: fibonacci-calculator
  env: fibonacci-dev
  bucket_name: elasticbeanstalk-us-east-1-349511673648
  bucket_path: fibonacci
  on:
    branch: staging
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
