---
version: '3'
services:
  fib-postgres:
    image: library/postgres:latest
    environment:
      - POSTGRES_PASSWORD=fibonaccipassword

  fib-redis:
    image: library/redis:latest
    command:
      - --loglevel warning

  fib-backend:
    image: oraserv/fib-backend:pro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=fib-postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=fibonaccipassword
    depends_on:
      - fib-postgres
      - fib-redis

  fib-worker:
    image: oraserv/fib-worker:pro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - fib-postgres
      - fib-redis

  fib-frontend:
    image: oraserv/fib-frontend:pro
    depends_on:
      - fib-postgres
      - fib-redis
      - fib-backend
      - fib-worker
    stdin_open: true

  nginx:
    image: oraserv/fib-nginx:pro
    depends_on:
      - fib-backend
      - fib-worker
      - fib-frontend
      - fib-redis
      - fib-postgres
    ports:
    - 80:80
